#!/bin/bash

git-rebase() {
  if ! is_git_repo; then
    echo "No git repository found"
    return;
  fi
  git rebase -i $(git log --color=always --abbrev=7 --format='%C(auto)%h %an %C(blue)%s %C(yellow)%cr' | fzf --ansi +m | cut -d' ' -f1)
}
git-rebase $@